name: "Remote Debug"

on:
  push:
    branches:
      - '*'

jobs:
  debug:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci(debug)')"
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v3
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: mdelillo/ssh-server-action@v1
        with:
          ngrok-authtoken: ${{ secrets.NGROK_TOKEN }}
          ssh-public-key: ${{ secrets.NGROK_SSH_RSA_PUB }}